# Generated by Django 4.2.2 on 2023-12-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='isdone',
        ),
    ]
